events {}

http {
    server {
        listen 80;

        # MERN frontend
        location /app/ {
            proxy_pass http://frontend/;
        }

        # LAMP (PHP)
        location /legacy/ {
            proxy_pass http://lamp/;
        }
    }
}
